name: Test Tasks

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install libgeos-dev libblas-dev liblapack-dev libatlas-base-dev gfortran
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Black
      run: |
        black .
    - name: Test tasks
      run: |
        ward
